# Generated by Django 3.1.4 on 2020-12-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevatormain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='door_speed',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='elevator',
            name='movement_speed',
            field=models.IntegerField(default=1),
        ),
    ]
