# Generated by Django 3.1.4 on 2020-12-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevatormain', '0004_building_active_elevators'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='active',
            field=models.IntegerField(default=1),
        ),
    ]
