# Generated by Django 3.1.4 on 2020-12-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevatormain', '0005_elevator_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='requests',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
