# Generated by Django 3.1.4 on 2020-12-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevatormain', '0006_building_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='request',
            field=models.CharField(default='[]', max_length=10),
        ),
        migrations.AlterField(
            model_name='building',
            name='requests',
            field=models.CharField(default='[]', max_length=50),
        ),
    ]
