# Generated by Django 3.1.4 on 2020-12-03 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevatormain', '0007_auto_20201203_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevator_id', models.IntegerField(default=0)),
                ('action', models.CharField(default='', max_length=100)),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 12, 3, 11, 32, 28, 126864))),
            ],
        ),
    ]
