# Generated by Django 3.1.4 on 2020-12-03 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevatormain', '0008_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 3, 11, 36, 40)),
        ),
    ]
